<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;
use MyProject\Proxies\__CG__\OtherProject\Proxies\__CG__\stdClass;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepository extends EntityRepository
{
	public function helloWorld(){
		
		$em = $this->_em;
		
		$qb = $em->createQueryBuilder();
		$qb->select("h");
		$qb->from("Entities\Hotel", "h");
		//$qb->setFirstResult( 0 );
		//$qb->setMaxResults( 1 );
		$qb->where('h.id = :identifier');
		
		$qb->setParameter('identifier', 185895);
		
		$result = $qb->setMaxResults(1)->getQuery();
		
		return $result->getResult()[0];
	}
	
	public function getHotels(){

		$em = $this->_em;
		
		$qb = $em->createQueryBuilder();
		
		$qb->select(array(
			"Hotel AS hotel",
			"COALESCE(HotelLang.name, Hotel.name) AS hotelName",
			"COALESCE(HotelLang.location, Hotel.location) AS hotelLocation"
		));
		
		$qb->from("Entities\Hotel", "Hotel");
		
		
		$qb->leftJoin(
			"Entities\HotelElGr", "HotelLang", 
			\Doctrine\ORM\Query\Expr\Join::WITH,
			"HotelLang = Hotel" 
		);
			
		
		$qb->innerJoin(
			"Entities\RegionHotelMapping", "HotelRegionMapping",
			\Doctrine\ORM\Query\Expr\Join::WITH,
			"HotelRegionMapping.hotel = Hotel"
		);
		
		$qb->andWhere("HotelRegionMapping.regionID in (:regions)");
		$qb->setParameter('regions', array(800001));
		
		//$result = $qb->setMaxResults(200)->getQuery();
		$paginator = new \Doctrine\ORM\Tools\Pagination\Paginator($qb->getQuery(), $fetchJoinCollection = true);
		$pageSize = 50;
		$totalItems = count($paginator);
		$pagesCount = ceil($totalItems / $pageSize);
		
		$results = $paginator->getQuery()
					->setFirstResult($pageSize * 0)
					->setMaxResults($pageSize)
					->getResult();
		
		//$return = new \stdClass();
		return $paginator;
		
		//return $return;
		
		
		//return $result->getResult();
	}
	
	public function getHotelAmenities(){
		
		$em = $this->_em;
		
		$qb = $em->createQueryBuilder();
		
		$qb->select(array(
			"COALESCE(AttributeLang.description, Attribute.description) as description", 
			"COALESCE(HotelAttributeMappingElGr.appendTxt, HotelAttributeMapping.appendTxt) as value"
		));
		$qb->from("Entities\HotelAttribute", "Attribute");

		$qb->leftJoin(
			"Entities\HotelAttributeElGr", "AttributeLang",
			\Doctrine\ORM\Query\Expr\Join::WITH,
			"AttributeLang.id = Attribute.id"
		);
		
		$qb->innerJoin(
			"Entities\AttributeHotelMapping", "HotelAttributeMapping",
			\Doctrine\ORM\Query\Expr\Join::WITH,
			"HotelAttributeMapping.attribute = Attribute"
		);
		
		$qb->leftJoin(
			"Entities\AttributeHotelMappingElGr", "HotelAttributeMappingElGr",
			\Doctrine\ORM\Query\Expr\Join::WITH,
			$qb->expr()->andX(
            	$qb->expr()->eq('HotelAttributeMappingElGr.attributeID', 'Attribute.id'),
                $qb->expr()->eq('HotelAttributeMappingElGr.eanHotelID', 'HotelAttributeMapping.eanHotelID')
            )
		);
		
		$qb->innerJoin(
			"Entities\Hotel", "Hotel",
			\Doctrine\ORM\Query\Expr\Join::WITH,
			"Hotel.id = HotelAttributeMapping.eanHotelID"
		);
		
		$qb->andWhere("Hotel.id = :hotelID");
		$qb->setParameter('hotelID', 182141);
		
		$result = $qb->setMaxResults(200)->getQuery();
		
		return $result->getResult();
	} 
}
